#print("Week 2 In Class Assignment")
hours = input("How many hours did you work?")
rate = input("What rate were you working at?")
total = int(hours) * int(rate)
print("You made", total, "dollars")
